name: Validate Build

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Build Application
        run: |
          npm ci
          npm run build
