name: Validate Lint & Prettier

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  lint_validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Run Lint & Prettier
        run: |
          npm ci
          npm run validate
