name: Run Tests

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test_run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Installing Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test Application
        run: |
          npm ci
          npm run test
